name: Build

on:
  push:
    branches:
      - master

env:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "11076708"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Android SDK & Install Components
        uses: android-actions/setup-android@v4
        with:
          cmdline-tools-version: ${{ env.ANDROID_SDK_TOOLS }}
          packages: platforms;android-${{ env.ANDROID_COMPILE_SDK }} platform-tools build-tools;${{ env.ANDROID_BUILD_TOOLS }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Inject Keystore and Key Properties
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > release.p12
          echo "${{ secrets.KEY_PROPERTIES }}" > key.properties

      - name: Build Release APK
        run: ./gradlew assembleBaseRelease

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: app
          path: app/build/outputs/
